// cards.js — data for the Mystery tarot app.
// AREAS: the areas of life a querent can ask about.
// DECK: the 22 Major Arcana, each with hand-written meanings for every
// area in both upright and reversed orientations.

export const AREAS = [
  { key: "general", label: "General", icon: "🔮" },
  { key: "love", label: "Love", icon: "💞" },
  { key: "career", label: "Career", icon: "⚒️" },
  { key: "money", label: "Money", icon: "💰" },
  { key: "health", label: "Health", icon: "🌿" },
  { key: "spirit", label: "Spirit", icon: "✨" },
];

// ZODIAC: Western tropical signs with inclusive [month, day] start dates,
// each with a one-line note used to colour an optional birth-date reading.
export const ZODIAC = [
  { sign: "Capricorn", emoji: "♑", start: [12, 22], note: "grounded, patient, and quietly ambitious" },
  { sign: "Aquarius", emoji: "♒", start: [1, 20], note: "inventive, independent, and future-facing" },
  { sign: "Pisces", emoji: "♓", start: [2, 19], note: "intuitive, tender, and deeply imaginative" },
  { sign: "Aries", emoji: "♈", start: [3, 21], note: "bold, pioneering, and quick to act" },
  { sign: "Taurus", emoji: "♉", start: [4, 20], note: "steadfast, sensual, and devoted to comfort" },
  { sign: "Gemini", emoji: "♊", start: [5, 21], note: "curious, expressive, and mentally agile" },
  { sign: "Cancer", emoji: "♋", start: [6, 21], note: "nurturing, loyal, and led by feeling" },
  { sign: "Leo", emoji: "♌", start: [7, 23], note: "warm, radiant, and generous of heart" },
  { sign: "Virgo", emoji: "♍", start: [8, 23], note: "discerning, thoughtful, and quietly devoted" },
  { sign: "Libra", emoji: "♎", start: [9, 23], note: "harmonious, fair-minded, and relational" },
  { sign: "Scorpio", emoji: "♏", start: [10, 23], note: "intense, perceptive, and transformative" },
  { sign: "Sagittarius", emoji: "♐", start: [11, 22], note: "adventurous, honest, and seeking meaning" },
];

// LIFE_PATH: numerology meanings keyed by reduced life-path number,
// including the master numbers 11, 22, and 33.
export const LIFE_PATH = {
  1: "a path of leadership and bold new beginnings",
  2: "a path of partnership, balance, and gentle diplomacy",
  3: "a path of creativity, expression, and joy",
  4: "a path of discipline, structure, and steady building",
  5: "a path of freedom, change, and adventure",
  6: "a path of love, responsibility, and care for others",
  7: "a path of seeking, wisdom, and inner truth",
  8: "a path of power, abundance, and worldly mastery",
  9: "a path of compassion, completion, and service",
  11: "a master path of intuition, inspiration, and spiritual insight",
  22: "a master path of the visionary builder turning dreams into form",
  33: "a master path of the compassionate teacher and healer",
};

export const DECK = [
  {
    id: "fool",
    number: 0,
    name: "The Fool",
    symbol: "🌅",
    keywords: { upright: "beginnings, innocence, leap of faith", reversed: "recklessness, hesitation, foolishness" },
    upright: {
      general: "A fresh beginning calls; step into the unknown with an open, trusting heart.",
      love: "New romance or a spontaneous reset — let your guard down and follow the spark.",
      career: "An exciting new path opens; say yes before you feel fully ready.",
      money: "A bold but unproven venture beckons; risk a little, learn quickly.",
      health: "Renewed vitality and a clean slate — adopt a playful, adventurous routine.",
      spirit: "Begin your journey with childlike wonder; the path reveals itself as you walk.",
    },
    reversed: {
      general: "You are leaping without looking; pause and check the ground beneath you.",
      love: "Cold feet or careless flirtation is destabilizing things; be honest about intentions.",
      career: "Naïve choices or skipped preparation could cost you; plan before you jump.",
      money: "Impulsive spending or a rash gamble threatens your stability — slow down.",
      health: "Ignoring small warnings invites bigger trouble; stop neglecting yourself.",
      spirit: "You are dodging the lesson; the same beginning will keep returning until you learn.",
    },
  },
  {
    id: "magician",
    number: 1,
    name: "The Magician",
    symbol: "🪄",
    keywords: { upright: "manifestation, willpower, skill", reversed: "manipulation, scattered focus, illusion" },
    upright: {
      general: "You hold every tool you need; focused will turns intention into reality.",
      love: "Magnetic attraction and clear communication can shape the relationship you want.",
      career: "Your talents align perfectly with the moment — act with confident purpose.",
      money: "Resourcefulness creates opportunity; channel your skill into tangible gain.",
      health: "Mind and body cooperate — small disciplined actions yield real results.",
      spirit: "As above, so below: you are a conduit between intention and the material world.",
    },
    reversed: {
      general: "Power is being misused or wasted; align your actions with honest intent.",
      love: "Charm masks manipulation or mixed signals — look past the performance.",
      career: "Scattered effort and unkept promises undercut you; focus your energy.",
      money: "A too-good-to-be-true offer hides a trick; verify before you commit.",
      health: "Quick fixes and false cures distract you from what actually heals.",
      spirit: "You are tricking yourself; reconnect your skills to a sincere purpose.",
    },
  },
  {
    id: "high-priestess",
    number: 2,
    name: "The High Priestess",
    symbol: "🌙",
    keywords: { upright: "intuition, mystery, inner voice", reversed: "secrets, disconnection, doubt" },
    upright: {
      general: "Answers live in your intuition, not the noise; listen to the quiet knowing.",
      love: "An unspoken bond deepens; trust subtle feelings over loud declarations.",
      career: "The wisest move is patient observation — gather what is hidden before acting.",
      money: "A financial truth is veiled; sense the undercurrent before you decide.",
      health: "Tune into your body's quiet signals; rest and inner stillness restore you.",
      spirit: "The veil thins — meditation and dreams carry messages meant for you alone.",
    },
    reversed: {
      general: "You are ignoring your inner voice or drowning it out; reconnect to silence.",
      love: "Secrets or withheld feelings cloud the bond; honesty must replace mystery.",
      career: "Information is being hidden from you, or your instincts feel muffled.",
      money: "Hidden details distort the picture; do not decide while half-informed.",
      health: "You are out of sync with your body; stop overriding what it tells you.",
      spirit: "Spiritual disconnection leaves you grasping; return to quiet practice.",
    },
  },
  {
    id: "empress",
    number: 3,
    name: "The Empress",
    symbol: "🌹",
    keywords: { upright: "abundance, nurturing, creativity", reversed: "smothering, blockage, neglect" },
    upright: {
      general: "Life is fertile and generous now; nurture what you want to see grow.",
      love: "Warmth, sensuality, and devotion blossom — love is given and received freely.",
      career: "Creative projects flourish; a nurturing, collaborative effort bears fruit.",
      money: "Abundance flows in; reinvest with care and let prosperity compound.",
      health: "Vitality and fertility are strong; honor your body with comfort and good food.",
      spirit: "Connect to the creative, life-giving force; beauty is a doorway to the sacred.",
    },
    reversed: {
      general: "Growth is stalled by neglect or over-control; tend your roots gently.",
      love: "Smothering or codependence chokes the bond; give it room to breathe.",
      career: "Creative blocks and burnout set in; you cannot pour from an empty cup.",
      money: "Overspending on comfort, or scarcity thinking, drains your resources.",
      health: "Self-neglect shows; you have been caring for everyone but yourself.",
      spirit: "Disconnection from nature and creativity leaves you depleted — replenish.",
    },
  },
  {
    id: "emperor",
    number: 4,
    name: "The Emperor",
    symbol: "🏛️",
    keywords: { upright: "structure, authority, stability", reversed: "control, rigidity, domination" },
    upright: {
      general: "Build solid foundations; discipline and clear order bring lasting stability.",
      love: "Commitment and steadiness anchor the relationship; show up reliably.",
      career: "Leadership and structure pay off — take charge and set firm boundaries.",
      money: "Disciplined planning secures your future; budget like a wise ruler.",
      health: "Routine and structure strengthen you; consistency is the real medicine.",
      spirit: "Ground your practice in order; structure is the trellis your spirit climbs.",
    },
    reversed: {
      general: "Rigidity or domination is backfiring; loosen your grip and stay flexible.",
      love: "Controlling behavior or coldness strains the bond; lead with warmth, not rule.",
      career: "An overbearing authority — yours or someone else's — blocks progress.",
      money: "Inflexible plans or reckless authority destabilize your finances.",
      health: "Pushing too hard or refusing to adapt is harming you; ease the rigidity.",
      spirit: "You are forcing control where surrender is needed; release the iron grip.",
    },
  },
  {
    id: "hierophant",
    number: 5,
    name: "The Hierophant",
    symbol: "🗝️",
    keywords: { upright: "tradition, guidance, belonging", reversed: "rebellion, dogma, nonconformity" },
    upright: {
      general: "Lean on tradition and trusted guidance; a mentor or system can light the way.",
      love: "Commitment within shared values — convention and ritual strengthen the bond.",
      career: "Learn the established way; mentorship and structure accelerate your growth.",
      money: "Conventional, time-tested strategies protect and grow your wealth.",
      health: "Trust proven methods and qualified guidance over fads.",
      spirit: "Tradition offers a map; a teacher or lineage can deepen your practice.",
    },
    reversed: {
      general: "Question the rules; the conventional path may no longer fit who you are.",
      love: "Breaking from expectation — an unconventional bond seeks its own form.",
      career: "Challenge stale norms; rigid institutions may be holding you back.",
      money: "Old financial dogma fails you; seek fresh, unorthodox approaches.",
      health: "One-size-fits-all advice isn't working; find what's right for your body.",
      spirit: "Reject borrowed dogma and forge a personal, authentic belief.",
    },
  },
  {
    id: "lovers",
    number: 6,
    name: "The Lovers",
    symbol: "💕",
    keywords: { upright: "union, choice, harmony", reversed: "disharmony, imbalance, misalignment" },
    upright: {
      general: "A meaningful choice aligns you with your values; harmony follows true alignment.",
      love: "Deep union and mutual choice — a soulful, values-matched connection thrives.",
      career: "A partnership or pivotal decision aligns with what you truly want.",
      money: "Choose investments that match your values; aligned choices prosper.",
      health: "Balance of body and mind; choose habits that genuinely love your future self.",
      spirit: "Union of opposites within you brings wholeness; choose from the heart.",
    },
    reversed: {
      general: "Misalignment and indecision pull you apart; reconcile values with actions.",
      love: "Disharmony, mismatched values, or a third party strains the bond.",
      career: "A poor partnership or conflicted choice creates friction — realign.",
      money: "Choices that betray your values cost you peace and resources.",
      health: "Inner conflict and bad habits war against your wellbeing; restore balance.",
      spirit: "You are divided against yourself; integrate the parts you've disowned.",
    },
  },
  {
    id: "chariot",
    number: 7,
    name: "The Chariot",
    symbol: "🏇",
    keywords: { upright: "drive, willpower, victory", reversed: "stalling, scattered, no control" },
    upright: {
      general: "Harness opposing forces with focused will; determination carries you to victory.",
      love: "Pursue what you want with confidence; momentum moves the relationship forward.",
      career: "Drive and discipline win the day — steer hard toward your goal.",
      money: "Decisive control over your finances yields a hard-won win.",
      health: "Willpower and consistency push you past plateaus toward strength.",
      spirit: "Master your inner drives; channel their power in one chosen direction.",
    },
    reversed: {
      general: "You've lost the reins; scattered effort and no direction stall you out.",
      love: "Pushing too hard or pulling apart — the relationship lacks shared direction.",
      career: "Lack of focus or control derails momentum; regroup and recommit.",
      money: "Impulsive, uncontrolled decisions send your finances off course.",
      health: "Inconsistency or burnout undoes your progress; steady the wheel.",
      spirit: "Conflicting urges drag you in circles; unify your will before moving.",
    },
  },
  {
    id: "strength",
    number: 8,
    name: "Strength",
    symbol: "🦁",
    keywords: { upright: "courage, patience, inner power", reversed: "self-doubt, weakness, raw force" },
    upright: {
      general: "Gentle courage conquers more than force; master the moment with calm patience.",
      love: "Compassion and patience tame conflict; quiet strength deepens trust.",
      career: "Lead with composure and resilience; steady confidence wins respect.",
      money: "Patience and self-control protect your resources from rash impulse.",
      health: "Inner resilience supports recovery; be gentle but unwavering with yourself.",
      spirit: "Tame your inner beast with love, not force; soft power is true mastery.",
    },
    reversed: {
      general: "Self-doubt or raw temper undermines you; reclaim your gentle inner strength.",
      love: "Insecurity or volatility strains the bond; soothe the inner fear first.",
      career: "Lost confidence or forced control weakens your standing — steady yourself.",
      money: "Impatience and weak discipline lead to costly, emotional decisions.",
      health: "Depleted reserves and low morale; rebuild strength gently, without force.",
      spirit: "You wrestle yourself instead of befriending your nature; ease the struggle.",
    },
  },
  {
    id: "hermit",
    number: 9,
    name: "The Hermit",
    symbol: "🏮",
    keywords: { upright: "introspection, solitude, guidance", reversed: "isolation, withdrawal, lost" },
    upright: {
      general: "Withdraw to find your light; solitude reveals the answer you already carry.",
      love: "Take space to know yourself; clarity within precedes a true connection.",
      career: "Step back and reflect; the wise next move comes from quiet contemplation.",
      money: "Pause and review your finances alone; reflection prevents costly haste.",
      health: "Rest and solitude restore you; listen inward and slow your pace.",
      spirit: "Seek inner truth in stillness; your own lamp lights the path for others.",
    },
    reversed: {
      general: "Solitude has curdled into isolation; it's time to reconnect with the world.",
      love: "Withdrawing too far leaves you lonely; let someone back in.",
      career: "Overthinking in isolation stalls you; seek counsel and re-engage.",
      money: "Avoiding your finances out of dread only deepens the problem.",
      health: "Excessive withdrawal feeds low spirits; gentle connection helps you heal.",
      spirit: "You've lost your way in seclusion; the answer needs the world, not retreat.",
    },
  },
  {
    id: "wheel-of-fortune",
    number: 10,
    name: "Wheel of Fortune",
    symbol: "🎡",
    keywords: { upright: "change, cycles, fate", reversed: "bad luck, resistance, stagnation" },
    upright: {
      general: "The wheel turns in your favor; embrace the shift and ride the rising cycle.",
      love: "A fateful turn brings the relationship to a new and fortunate phase.",
      career: "Lucky timing opens doors; seize the opportunity the cycle presents.",
      money: "A positive financial turn arrives — fortune favors your next move.",
      health: "A turning point toward recovery; the cycle bends toward improvement.",
      spirit: "Trust the rhythm of fate; you are exactly where the cycle means you to be.",
    },
    reversed: {
      general: "The cycle dips; resisting inevitable change only prolongs the difficulty.",
      love: "An unlucky phase or repeated patterns test the bond — break the loop.",
      career: "Bad timing or stagnation frustrates you; wait for the wheel to turn.",
      money: "A downturn or run of bad luck — protect your reserves and ride it out.",
      health: "A setback in the cycle; patience and care will turn things around.",
      spirit: "You fight against fate; surrender to the lesson the cycle is teaching.",
    },
  },
  {
    id: "justice",
    number: 11,
    name: "Justice",
    symbol: "⚖️",
    keywords: { upright: "fairness, truth, accountability", reversed: "injustice, dishonesty, imbalance" },
    upright: {
      general: "Truth and fairness prevail; your choices return to you in kind.",
      love: "Honesty and equality balance the relationship; fairness restores trust.",
      career: "A fair outcome or just decision rewards your integrity.",
      money: "Accounts balance and contracts hold; act with honesty and they protect you.",
      health: "Balance and cause-and-effect rule; honest habits yield honest results.",
      spirit: "Karmic balance is at work; align your actions with truth and conscience.",
    },
    reversed: {
      general: "Unfairness or avoided accountability distorts things; face the truth.",
      love: "Imbalance, blame, or dishonesty corrodes the bond — own your part.",
      career: "An unjust decision or broken agreement; gather facts and stand firm.",
      money: "Hidden costs, unfair terms, or dishonest dealings threaten you.",
      health: "Consequences of imbalance surface; correct the cause, not just the symptom.",
      spirit: "You are dodging accountability; integrity must be restored from within.",
    },
  },
  {
    id: "hanged-man",
    number: 12,
    name: "The Hanged Man",
    symbol: "🙃",
    keywords: { upright: "surrender, new perspective, pause", reversed: "stalling, resistance, indecision" },
    upright: {
      general: "Surrender control and shift your view; a willing pause reveals new insight.",
      love: "See the relationship from a new angle; patience and sacrifice deepen it.",
      career: "A strategic pause reframes the problem; let go to gain clarity.",
      money: "Hold off on big moves; a different perspective changes the whole calculation.",
      health: "Rest and release tension; surrendering the struggle aids healing.",
      spirit: "Let go to receive; suspended in stillness, wisdom turns right-side up.",
    },
    reversed: {
      general: "Needless delay and resistance trap you; release what you're clinging to.",
      love: "Stalling or martyrdom keeps the bond stuck; stop sacrificing in vain.",
      career: "Indecision and stagnation cost you; commit to a direction at last.",
      money: "Procrastinating on decisions deepens the bind — act, don't dangle.",
      health: "Resisting needed change prolongs discomfort; surrender the old way.",
      spirit: "You cling to control and miss the lesson; true insight needs your surrender.",
    },
  },
  {
    id: "death",
    number: 13,
    name: "Death",
    symbol: "🦋",
    keywords: { upright: "endings, transformation, rebirth", reversed: "resistance, clinging, stagnation" },
    upright: {
      general: "An ending clears the way for rebirth; let the old fall so the new can rise.",
      love: "A relationship transforms profoundly; release the old form to find renewal.",
      career: "One chapter closes so a truer path can begin — let it end gracefully.",
      money: "A financial chapter ends; clear the dead weight to make room for growth.",
      health: "Shed old habits completely; profound renewal follows true release.",
      spirit: "Ego-death and transformation — what dies in you makes space for the soul.",
    },
    reversed: {
      general: "You cling to what must end; resistance only prolongs the painful transition.",
      love: "Refusing to let go keeps a finished relationship on life support.",
      career: "Holding onto a dead role stalls your rebirth; allow the ending.",
      money: "Clinging to failing investments blocks renewal; cut the losses.",
      health: "Old patterns you won't release keep you stuck; change is overdue.",
      spirit: "Fear of transformation freezes you; surrender to the necessary death.",
    },
  },
  {
    id: "temperance",
    number: 14,
    name: "Temperance",
    symbol: "🍶",
    keywords: { upright: "balance, moderation, patience", reversed: "excess, imbalance, impatience" },
    upright: {
      general: "Blend opposites with patience; moderation and balance create harmony.",
      love: "Patience and compromise harmonize the relationship into a steady flow.",
      career: "Measured, balanced effort over time yields sustainable success.",
      money: "Moderation and steady saving build security without strain.",
      health: "Balance and gentle consistency restore wellbeing; avoid extremes.",
      spirit: "Find the middle way; alchemy happens when opposites are patiently blended.",
    },
    reversed: {
      general: "Excess and imbalance throw you off; restore moderation and patience.",
      love: "Impatience or extremes destabilize the bond; recover the steady middle.",
      career: "Overwork or erratic effort burns you out; rebalance your pace.",
      money: "Overindulgence or feast-and-famine cycles drain you — find moderation.",
      health: "Excess in some area harms you; return to balanced, measured habits.",
      spirit: "You've lost your center; patient recalibration brings you back.",
    },
  },
  {
    id: "devil",
    number: 15,
    name: "The Devil",
    symbol: "⛓️",
    keywords: { upright: "bondage, temptation, attachment", reversed: "release, awakening, freedom" },
    upright: {
      general: "You're bound by something you could release; name the chain you've chosen.",
      love: "Passion shades into obsession or dependency; examine unhealthy attachment.",
      career: "A golden-handcuffs trap holds you; the security may be a cage.",
      money: "Debt, greed, or materialism enslaves you; confront the compulsion.",
      health: "Addiction or harmful habits have a grip; awareness loosens the chain.",
      spirit: "You've mistaken the shadow for the self; the bondage is self-imposed.",
    },
    reversed: {
      general: "You're breaking free; awareness loosens the chains you once accepted.",
      love: "Releasing a toxic attachment restores your freedom and self-respect.",
      career: "You see the trap clearly and step out of the gilded cage.",
      money: "Breaking free of debt or compulsion — reclaim control of your resources.",
      health: "Recovery begins; you're loosening an addiction's hold on you.",
      spirit: "Awakening dispels the illusion; you reclaim power from your shadow.",
    },
  },
  {
    id: "tower",
    number: 16,
    name: "The Tower",
    symbol: "🗼",
    keywords: { upright: "upheaval, revelation, collapse", reversed: "averted disaster, fear of change" },
    upright: {
      general: "A sudden upheaval topples false foundations; the shock clears the way for truth.",
      love: "A revelation shakes the relationship; what wasn't real cannot stand.",
      career: "Abrupt disruption forces change; what was built on illusion falls.",
      money: "A sudden financial shock; rebuild on honest, solid ground.",
      health: "A wake-up call demands change; the crisis can become a turning point.",
      spirit: "A flash of truth shatters illusion; liberation often arrives as collapse.",
    },
    reversed: {
      general: "You're delaying an inevitable reckoning; fear of change prolongs the strain.",
      love: "Avoiding a needed confrontation keeps a cracked foundation standing.",
      career: "You narrowly avoid disruption, or cling to a structure already failing.",
      money: "A dodged crisis, or denial of mounting risk — address it before it bursts.",
      health: "Ignored warnings build pressure; heed the signs before the break.",
      spirit: "You resist the truth that would free you; the longer you wait, the harder it falls.",
    },
  },
  {
    id: "star",
    number: 17,
    name: "The Star",
    symbol: "⭐",
    keywords: { upright: "hope, renewal, inspiration", reversed: "despair, disconnection, doubt" },
    upright: {
      general: "Hope returns and healing flows; trust the quiet light guiding you onward.",
      love: "Renewed faith and tenderness; the relationship is gently restored.",
      career: "Inspiration and renewed purpose light your path; the future looks bright.",
      money: "Optimism is justified; steady renewal replenishes your resources.",
      health: "Healing and recovery are underway; hope itself is medicine.",
      spirit: "Reconnect to your guiding star; serenity and faith renew your spirit.",
    },
    reversed: {
      general: "Despair clouds your hope; reconnect to faith before doubt takes root.",
      love: "Discouragement dims the bond; tend the small flame of hope.",
      career: "Lost faith or inspiration stalls you; reconnect to your why.",
      money: "Pessimism distorts your view; the situation is better than you fear.",
      health: "Low morale slows healing; gentle hope is the first step back.",
      spirit: "Disconnection from meaning leaves you parched; return to the well.",
    },
  },
  {
    id: "moon",
    number: 18,
    name: "The Moon",
    symbol: "🌕",
    keywords: { upright: "illusion, intuition, the unknown", reversed: "clarity, release of fear, truth" },
    upright: {
      general: "Things aren't as they seem; let intuition guide you through the fog.",
      love: "Hidden feelings or confusion cloud the bond; trust instinct over appearance.",
      career: "Uncertainty and illusion obscure the path; don't decide in the dark.",
      money: "Unclear or deceptive numbers; sense what's hidden before committing.",
      health: "Anxiety and unclear symptoms — listen inward and seek clarity gently.",
      spirit: "The subconscious speaks in dreams and shadows; honor the mystery.",
    },
    reversed: {
      general: "The fog lifts; hidden truths surface and fear loses its grip.",
      love: "Confusion clears and secrets come to light; honesty restores the bond.",
      career: "Illusions dissolve and the real situation becomes clear at last.",
      money: "Deception is exposed; you finally see the numbers as they are.",
      health: "Anxiety eases as understanding grows; clarity calms the mind.",
      spirit: "You move from confusion to insight; the unconscious yields its message.",
    },
  },
  {
    id: "sun",
    number: 19,
    name: "The Sun",
    symbol: "☀️",
    keywords: { upright: "joy, success, vitality", reversed: "dimmed joy, delay, doubt" },
    upright: {
      general: "Radiant success and joy; clarity and warmth bless everything you touch.",
      love: "Warmth, joy, and openness — the relationship shines with genuine happiness.",
      career: "Recognition and success arrive; your efforts blaze into clear achievement.",
      money: "Prosperity and good fortune; abundance flows freely your way.",
      health: "Vitality and wellbeing radiate; energy and recovery are strong.",
      spirit: "Enlightenment and joyful clarity; you walk in the light of truth.",
    },
    reversed: {
      general: "The joy is muted or delayed; clear the small clouds blocking your sun.",
      love: "Temporary gloom or insecurity dims the warmth; happiness is recoverable.",
      career: "Success is delayed or unrecognized; keep shining, it will break through.",
      money: "Optimism outpaces reality; temper expectations and the gain will come.",
      health: "Lowered energy or lingering doubt; tend the small shadows to restore vitality.",
      spirit: "Self-doubt veils your light; remember your inner sun never truly sets.",
    },
  },
  {
    id: "judgement",
    number: 20,
    name: "Judgement",
    symbol: "📯",
    keywords: { upright: "awakening, reckoning, renewal", reversed: "self-doubt, avoidance, regret" },
    upright: {
      general: "A clear call to rise and renew; reckon honestly and step into rebirth.",
      love: "A turning point of forgiveness and honest reckoning revives the bond.",
      career: "A calling awakens; assess the past and answer the new summons.",
      money: "Reassess your finances honestly; a fresh, wiser chapter begins.",
      health: "A wake-up call to renewal; honest reckoning launches recovery.",
      spirit: "Hear the call to awaken; release the past and rise to your true purpose.",
    },
    reversed: {
      general: "Self-judgment or avoidance keeps you stuck; answer the call you've ignored.",
      love: "Lingering regret or refusal to forgive blocks renewal — let it go.",
      career: "Self-doubt makes you ignore your calling; stop second-guessing and rise.",
      money: "Avoiding an honest reckoning lets problems fester; face the books.",
      health: "Ignoring the wake-up call delays healing; heed it now.",
      spirit: "You judge yourself too harshly to awaken; forgiveness frees the path.",
    },
  },
  {
    id: "world",
    number: 21,
    name: "The World",
    symbol: "🌍",
    keywords: { upright: "completion, fulfillment, wholeness", reversed: "incompletion, shortcuts, delay" },
    upright: {
      general: "A cycle completes in triumph; you've arrived, whole and fulfilled.",
      love: "A relationship reaches joyful wholeness and lasting fulfillment.",
      career: "A major achievement crowns your efforts; the goal is fully realized.",
      money: "Financial goals are accomplished; abundance and security come full circle.",
      health: "Wholeness and vitality; a healing cycle reaches its complete restoration.",
      spirit: "Integration and fulfillment — you embody the wholeness you sought.",
    },
    reversed: {
      general: "You're close but not complete; finish what you started, no shortcuts.",
      love: "Something unresolved delays fulfillment; close the open loop honestly.",
      career: "A goal stalls just short of the finish; see it fully through.",
      money: "Financial closure is delayed; tie up the loose ends to complete the cycle.",
      health: "Recovery is nearly there; don't quit before you're whole.",
      spirit: "Lingering loose ends block integration; complete the inner work.",
    },
  },
];
